/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

function fiboEvenSum(n) {
  let series = [0, 1];
  let evenSum = 0;

  for (let i = 0; series[series.length - 1] < n; i++) {
    if (series[series.length - 2] + series[series.length - 1] <= n) {
      series.push(series[series.length - 2] + series[series.length - 1]);
    } else {
      break;
    }
  }

  for (let i = 0; i < series.length; i++) {
    if (series[i] % 2 == 0) {
      evenSum += series[i];
    }
  }
  return evenSum;
}
